services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - ${PORTAINER_PORT}:9000
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - ./homarr/data:/data
    ports:
      - ${HOMARR_PORT}:7575
  vault:
    container_name: vault
    image: vaultwarden/server:latest
    restart: always
    env_file: .env
    ports:
      - ${VAULT_PORT}:80
    volumes:
      - ./vw-data:/data
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=${QBITTORRENT_PORT}
    volumes:
      - ./qbittorrent/config:/config
      - ${QBITTORRENT_DOWNLOAD_PATH}:/downloads
    ports:
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}
    restart: unless-stopped
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    volumes:
      - ${FILEBROWSER_HOME_PATH}:/srv
      - ./filebrowser.json:/.filebrowser.json
    ports:
      - ${FILEBROWSER_PORT}:80
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VERSION=docker
    volumes:
      - ${MEDIA_APTH}library:/config
      - ${MEDIA_APTH}tvseries:/tv
      - ${MEDIA_APTH}movies:/movies
    ports:
      - ${PLEX_PORT}:32400
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./sonarr/config:/config
      - ${MEDIA_APTH}tvseries:/tv
      - ${QBITTORRENT_DOWNLOAD_PATH}:/downloads
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./prowlarr/config:/config
    ports:
      - ${PROWLARR_PORT}:9696
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Paris
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 

volumes:
  portainer_data:
