services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - ${PORTAINER_PORT}:9000
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - ./homarr/data:/data
    ports:
      - ${HOMARR_PORT}:7575
  vault:
    container_name: vault
    image: vaultwarden/server:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - ${VAULT_PORT}:80
    volumes:
      - ./vw-data:/data
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=${QBITTORRENT_PORT}
    volumes:
      - ./qbittorrent/config:/config
      - ${QBITTORRENT_DOWNLOAD_PATH}:/downloads
    ports:
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ${FILEBROWSER_HOME_PATH}:/srv
      - ./filebrowser.json:/.filebrowser.json
    ports:
      - ${FILEBROWSER_PORT}:80
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VERSION=docker
    restart: unless-stopped
    volumes:
      - ${MEDIA_APTH}library:/config
      - ${MEDIA_APTH}tvseries:/tv
      - ${MEDIA_APTH}movies:/movies
    ports:
      - ${PLEX_PORT}:32400
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./sonarr/config:/config
      - ${MEDIA_APTH}tvseries:/tv
      - ${QBITTORRENT_DOWNLOAD_PATH}:/downloads
    ports:
      - ${SONARR_PORT}:8989
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./radarr/config:/config
      - ${MEDIA_APTH}movies:/movies
      - ${QBITTORRENT_DOWNLOAD_PATH}:/downloads
    ports:
      - ${RADARR_PORT}:7878
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./prowlarr/config:/config
    ports:
      - ${PROWLARR_PORT}:9696
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Paris
    ports:
      - "${PORT:-8191}:8191"
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./overseerr/config:/config
    ports:
      - ${OVERSEERR_PORT}:5055
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - ./readarr/config:/config
      - ${MEDIA_APTH}books:/books
      - ${MEDIA_APTH}audiobooks:/audiobooks
      - ${QBITTORRENT_DOWNLOAD_PATH}:/downloads
    ports:
      - ${READARR_PORT}:8787
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    volumes:
      - ${MEDIA_APTH}audiobooks:/audiobooks
      - ${MEDIA_APTH}podcasts:/podcasts
      - ./audiobookshelf/config/:/config
      - ./audiobookshelf/metadata/:/metadata
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    environment:
      - TZ=Europe/Paris
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.10.2 # 
    container_name: mealie
    restart: unless-stopped
    ports:
        - "${MEALIE_PORT}:9000"
    volumes:
      - mealie-data:/app/data/
    environment:
      ALLOW_SIGNUP: true
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: http://localhost

volumes:
  mealie-data:
  portainer_data:
